### ISSUE TITLE
Error on basic tutorials

### ISSUE THREAD

**Issue by PJTraveler** [edwardvmills/Silk#17]
I'm using the NURBLsLib tutorials on SILK in 
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23463 (Git)
Build type: Release
Branch: master
Hash: adc6db8f32c17e9f67cb82aa7962d1e42ce061c6
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)
![2020-12-27_20-33-53](https://user-images.githubusercontent.com/63062762/103189758-1975d380-4883-11eb-818c-94d6d8c2e509.png)

When trying to create a control polygon and then curve I get the errors shown in the screen capture

**Comment by edwardvmills** [comment]
I think you selected the sketch when you clicked the CubicCurve_4 button.

You should select the ControlPoly4_3L object in the tree, then click the CubicCurve_4 button

the entities progress as follows:
Sketch > ControlPoly > CubicCurve
not Sketch > CubicCurve

**Comment by edwardvmills** [comment]
reference [https://github.com/edwardvmills/NURBSlib_EVM/blob/gh-pages/Tutorial%200.01%20ControlPoly4%20and%20CubicCurve4.md](url)
step 3 
"Select the ControlPoly_3L object and click the CubicCurve4 macro (now a WB icon)"

**Comment by edwardvmills** [comment]
another thing to note: in order to do live adjustment of the curves/surfaces while dragging and dropping within the controlling sketch, you have to change a property of the sketch (properties are on the data tab in the combo view):
in the "visibility automation section, set "hide dependent" to "false". 

otherwise the control poly and curve disappear when you enter the sketch.

**Comment by PJTraveler** [comment]
Thanks !:-)I'll try it and the other suggestions-----Original Message-----

**Comment by PJTraveler** [comment]
You were correct I had the wrong object selected. 

 

I’m working on tutorial2 and having  an issue/comments.

1.	In tutorial 2 step 3 when we do the copy/paste, you need to change the selection to the encompassing folder (ControGrid44 and….) before doing the paste, otherwise the front profile zx is in the wrong place  (or doesn’t match the diagram)
2.	It is not clear what order things need to be clicked on in the model tree so that attachment will work.  It only seems to work if a) issue 1 is fixed, b) that the order of clicks is important first select Anchor xy001, then the attachment menu (from Part), and finally the left most point.    This results in ‘Sketch:Vertex1
3.	In the attachment dialog in ver 0.19 doesn’t seem to work quite the same way as in the tutorial. You must click on the bolded ‘Translate Origin’  in the attachment mode box to get the light blue to actually move. 
4.	In Step 4, after the recalc, only the yellow is added to the left point, but no red (see pic) and there is, I think, a recalc flag on ‘merge01’. However, it doesn’t respond to recalc.

Thanks for the support,

Patrick

**Comment by edwardvmills** [comment]
1. sure, select top level or click a blank spot in the tree or 3D viewport to deselect the folder we just copied. Then when you paste it will go to the top level. you can also drag the folder somewhere else even if you pasted it into the source folder.
i could not reproduce your zx plane error just from a paste operation. everything seemed to be in the right spot.

2. the tutorial says to edit the attachment of "Anchor - xy001" and only this attachment. this moves everything, then you can edit the sketches themselves. BUT! the problem here is FreeCAD has changed its behavior since i made this model. My zx sketch used to be just fine, but now reports as overconstrained. so i went in the sketcher, selected and deleted the constraint FreeCAD suggested, exited the sketch and now everything works.

3. yeah FreeCAD changes fast. These tutorials are tutorials for the Silk tools themselves, and require the user to have the FreeCAD side of things under control.

4. if things don't move after attachment, this could be the  (now) overconstrained sketch. i can't see any pictures in your post, so i'm not sure how to interpret it.  In my case, zx sketch constraint 9 reported as overconstrained, so i deleted it, and then everything updated correctly and moved to follow the base sketch

**Comment by PJTraveler** [comment]
Thanks for taking the time to respond :-)-----Original Message-----
